### ISSUE TITLE
repo downloads outdated tripal release

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_install#6]
unless im mistaken rapid install downloads rc3.

rather than hardcoding fix it woudl be great if it could download the latest release instead.

**Comment by spficklin** [comment]
Issue has been resolved:

https://github.com/tripal/tripal_install/blob/4ca0acf7465b07d918ec684353e9a887a4a33942/tripal_install.drush.inc#L112

https://github.com/tripal/tripal_install/blob/4ca0acf7465b07d918ec684353e9a887a4a33942/tripal_install.drush.inc#L138-L140
